#/opt/portainer/portainer.yml 
version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - 9000:9000
    volumes:
      - portainer_data:/data
    networks:
      - portainer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - portainer.agent=true
        - traefik.enable=false

volumes:
  portainer_data:

networks:
  portainer:
    driver: overlay